[project]
name = "provecta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "starlette>=0.50.0",
    "uvicorn[standard]>=0.38.0",
    "watchdog>=6.0.0",
]
